# Generated by Django 4.0.4 on 2022-08-22 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst',
            name='app_from',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gst',
            name='applicable_form',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gst',
            name='applicable_from',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gst',
            name='gst_applicable',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
