# Generated by Django 4.0.2 on 2022-08-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_items_receivable'),
    ]

    operations = [
        migrations.CreateModel(
            name='payitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.CharField(max_length=255)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
