# Generated by Django 4.0.4 on 2022-08-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_gst_taxability_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst_taxability',
            name='applicable_dt',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
