# Generated by Django 4.0.4 on 2022-08-22 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_gst_taxability_applicable_dt'),
    ]

    operations = [
        migrations.CreateModel(
            name='currencyAlteration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Symbol', models.CharField(max_length=255)),
                ('FormalName', models.CharField(max_length=255)),
                ('ISOCurrency', models.CharField(max_length=30, null=True)),
                ('DecimalPlace', models.IntegerField()),
                ('showAmount', models.CharField(max_length=20)),
                ('suffixSymbol', models.CharField(max_length=20)),
                ('AddSpace', models.CharField(max_length=20)),
                ('wordRep', models.CharField(max_length=255, null=True)),
                ('DecimalWords', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='rateofexchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_ROE', models.DateField(null=True)),
                ('currencyName', models.CharField(max_length=100, null=True)),
                ('std_rate', models.CharField(max_length=100, null=True)),
                ('sell_voucher_rate', models.CharField(max_length=100, null=True)),
                ('sell_specified_rate', models.CharField(max_length=100, null=True)),
                ('buy_specified_rate', models.CharField(max_length=100, null=True)),
                ('buy_voucher_rate', models.CharField(max_length=100, null=True)),
                ('currencyAlteration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.currencyalteration')),
            ],
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher_name', models.CharField(max_length=255, null=True)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('voucher_type', models.CharField(max_length=255, null=True)),
                ('abbreviation', models.CharField(max_length=255, null=True)),
                ('voucherActivate', models.CharField(max_length=20, null=True)),
                ('voucherNumber', models.CharField(max_length=200, null=True)),
                ('preventDuplicate', models.CharField(max_length=20, null=True)),
                ('advance_con', models.CharField(max_length=20, null=True)),
                ('voucherEffective', models.CharField(max_length=20, null=True)),
                ('transaction', models.CharField(max_length=20, null=True)),
                ('make_optional', models.CharField(max_length=20, null=True)),
                ('voucherNarration', models.CharField(max_length=20, null=True)),
                ('provideNarration', models.CharField(max_length=20, null=True)),
                ('manu_jrnl', models.CharField(max_length=20, null=True)),
                ('track_purchase', models.CharField(max_length=20, null=True)),
                ('enable_acc', models.CharField(max_length=20, null=True)),
                ('prnt_VA_save', models.CharField(max_length=20, null=True)),
                ('prnt_frml', models.CharField(max_length=20, null=True)),
                ('jurisdiction', models.CharField(max_length=20, null=True)),
                ('title_print', models.CharField(max_length=20, null=True)),
                ('set_alter', models.CharField(max_length=20, null=True)),
                ('pos_invoice', models.CharField(max_length=20, null=True)),
                ('msg_1', models.CharField(max_length=255, null=True)),
                ('msg_2', models.CharField(max_length=255, null=True)),
                ('default_bank', models.CharField(max_length=255, null=True)),
                ('name_class', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='crt_currency',
            new_name='company_alt_currency',
        ),
        migrations.DeleteModel(
            name='alt_currency',
        ),
        migrations.DeleteModel(
            name='currency_ROE',
        ),
        migrations.DeleteModel(
            name='tally_vouchers',
        ),
        migrations.RenameField(
            model_name='cost_centre',
            old_name='centre_alias',
            new_name='cname',
        ),
        migrations.RenameField(
            model_name='cost_centre',
            old_name='centre_name',
            new_name='cost_alias',
        ),
        migrations.RenameField(
            model_name='cost_centre',
            old_name='centre_under',
            new_name='under',
        ),
        migrations.RemoveField(
            model_name='cost_centre',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tally_group',
            name='company',
        ),
    ]
