# Generated by Django 4.0.2 on 2022-08-29 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_payable'),
    ]

    operations = [
        migrations.CreateModel(
            name='grunder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('und', models.CharField(max_length=255)),
            ],
        ),
    ]
