# Generated by Django 4.0.2 on 2022-08-22 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_currencyalteration_rateofexchange_voucher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency_alt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stddate', models.CharField(blank=True, max_length=255, null=True)),
                ('stdrate', models.CharField(default='null', max_length=255)),
                ('selldate', models.CharField(blank=True, max_length=255, null=True)),
                ('selvorate', models.CharField(default='null', max_length=255)),
                ('sellrate', models.CharField(default='null', max_length=255)),
                ('buydate', models.CharField(blank=True, max_length=255, null=True)),
                ('buyvorate', models.CharField(default='null', max_length=255)),
                ('buyrate', models.CharField(default='null', max_length=255)),
                ('currencyAlteration', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.currencyalteration')),
            ],
        ),
    ]
