# Generated by Django 4.0.2 on 2022-08-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_groupmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ledgercreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('alias', models.CharField(max_length=255, null=True)),
                ('under', models.CharField(max_length=255)),
                ('bank_details', models.CharField(max_length=255)),
                ('mname', models.CharField(max_length=255, null=True)),
                ('address', models.CharField(max_length=255, null=True)),
                ('country', models.CharField(max_length=255, null=True)),
                ('state', models.CharField(max_length=255, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('pan_no', models.IntegerField(null=True)),
                ('registration_type', models.CharField(max_length=255, null=True)),
                ('gst_uin', models.IntegerField(null=True)),
                ('set_alter_gstdetails', models.CharField(max_length=255, null=True)),
            ],
        ),
    ]
