# Generated by Django 4.0.2 on 2022-08-29 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_ledgercreation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledgercreation',
            name='Alter_GST_Details',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='Appropriate',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='Echeque_p',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='GST_Applicable',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='SA_cheque_bk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='Types_of_supply',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='ac_holder_nm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='acc_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='balance_billbybill',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='credit_period',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='creditdays_voucher',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='ifsc_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_Echeque_p',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_SA_cheque_bk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_ac_holder_nm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_acc_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_ifsc_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_set_odl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='occ_swift_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_Echeque_p',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_SA_cheque_bk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_ac_holder_nm',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_acc_no',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_branch',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_ifsc_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_set_odl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='od_swift_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='percentage_of_calcution',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='rond_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='rond_method',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='rounding_limit',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='rounding_method',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='statutory_details',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='swift_code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='tax_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='type_duty_tax',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ledgercreation',
            name='type_of_ledger',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
