# Generated by Django 4.0.2 on 2022-08-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_cost_center'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='d_path',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
