# Generated by Django 4.0.2 on 2022-08-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_cred'),
    ]

    operations = [
        migrations.CreateModel(
            name='led',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('openam', models.IntegerField()),
                ('penam', models.IntegerField()),
                ('due', models.DateField()),
                ('overd', models.IntegerField()),
            ],
        ),
    ]
