# Generated by Django 4.0.2 on 2022-08-31 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_led'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='password',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
