# Generated by Django 4.0.2 on 2022-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0011_auto_20220825_1248'),
    ]

    operations = [
        migrations.CreateModel(
            name='allocate_stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocate', models.CharField(max_length=100, null=True)),
                ('for_allocate', models.CharField(max_length=100, null=True)),
                ('godown', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('per', models.CharField(max_length=100, null=True)),
                ('amount', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='attendance_crt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('under_name', models.CharField(max_length=50, null=True)),
                ('attendance', models.CharField(max_length=50, null=True)),
                ('period', models.CharField(max_length=50, null=True)),
                ('units', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accno', models.CharField(max_length=50)),
                ('ifsc_Code', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='bank_crt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accno', models.CharField(max_length=50)),
                ('ifsc_Code', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=50)),
                ('branch', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('under_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CreateEmployeeGrp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('under_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='CreateGodown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('under_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='employee_crt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('alias', models.CharField(max_length=100)),
                ('under_name', models.CharField(max_length=50)),
                ('doj', models.CharField(max_length=30)),
                ('salary', models.CharField(max_length=50)),
                ('empno', models.CharField(max_length=20)),
                ('designation', models.CharField(max_length=20)),
                ('function_name', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=20)),
                ('dob', models.CharField(max_length=20)),
                ('bld_grp', models.CharField(max_length=20)),
                ('father_mother', models.CharField(max_length=20)),
                ('spouse', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phn', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('bank', models.CharField(max_length=50)),
                ('incometax', models.CharField(max_length=20)),
                ('adhar', models.CharField(max_length=20)),
                ('uan', models.CharField(max_length=20)),
                ('pf', models.CharField(max_length=20)),
                ('pr', models.CharField(max_length=20)),
                ('esi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='pancin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pan', models.CharField(max_length=30)),
                ('cin', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='payhead_crt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('payhead_type', models.CharField(max_length=100, null=True)),
                ('income_type', models.CharField(max_length=100, null=True)),
                ('under_name', models.CharField(max_length=100, null=True)),
                ('net_salary', models.CharField(max_length=100, null=True)),
                ('pay_slip_name', models.CharField(max_length=100, null=True)),
                ('currency_ledger', models.CharField(max_length=100, null=True)),
                ('calculation_type', models.CharField(max_length=100, null=True)),
                ('attendance_type', models.CharField(max_length=100, null=True)),
                ('production_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='payroll_crt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('allias', models.CharField(max_length=100, null=True)),
                ('voucher_type', models.CharField(max_length=100, null=True)),
                ('abbreviation', models.CharField(max_length=100, null=True)),
                ('activate_voucher', models.CharField(max_length=100, null=True)),
                ('voucher_numbering_method', models.CharField(max_length=100, null=True)),
                ('effective_dates', models.CharField(max_length=100, null=True)),
                ('narration_voucher', models.CharField(max_length=100, null=True)),
                ('print_voucher', models.CharField(max_length=100, null=True)),
                ('classs', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Price_level_crt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='salary_crt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('alias', models.CharField(max_length=50, null=True)),
                ('date', models.CharField(max_length=100, null=True)),
                ('pay_head_name', models.CharField(max_length=100, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('pay_head_type', models.CharField(max_length=100, null=True)),
                ('calculation_type', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='stock_item_crt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('alias', models.CharField(max_length=100, null=True)),
                ('under', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(max_length=100, null=True)),
                ('units', models.CharField(max_length=100, null=True)),
                ('batches', models.CharField(max_length=100, null=True)),
                ('manufacturing_date', models.CharField(max_length=100, null=True)),
                ('expiry_dates', models.CharField(max_length=100, null=True)),
                ('rate_of_duty', models.CharField(max_length=100, null=True)),
                ('quantity', models.CharField(max_length=100, null=True)),
                ('rate', models.CharField(max_length=100, null=True)),
                ('per', models.CharField(max_length=100, null=True)),
                ('value', models.CharField(max_length=100, null=True)),
                ('additional', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitCrt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, null=True)),
                ('symbol', models.CharField(max_length=20, null=True)),
                ('formal_name', models.CharField(max_length=50, null=True)),
                ('uqc', models.CharField(max_length=50, null=True)),
                ('decimal', models.IntegerField(null=True)),
                ('first_unit', models.CharField(max_length=50, null=True)),
                ('conversion', models.CharField(max_length=30, null=True)),
                ('second_unit', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='createstockcateg',
            old_name='under',
            new_name='under_name',
        ),
        migrations.RemoveField(
            model_name='createstockcateg',
            name='category',
        ),
        migrations.RemoveField(
            model_name='createstockcateg',
            name='quantities',
        ),
        migrations.RemoveField(
            model_name='createstockgrp',
            name='group',
        ),
        migrations.RemoveField(
            model_name='createstockgrp',
            name='under',
        ),
        migrations.AddField(
            model_name='createstockgrp',
            name='under_name',
            field=models.CharField(default=2, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createstockgrp',
            name='quantities',
            field=models.CharField(max_length=50),
        ),
    ]
