# Generated by Django 4.0.2 on 2022-08-26 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_allocate_stock_attendance_crt_bank_bank_crt_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journalledger', models.CharField(max_length=225, null=True)),
                ('journal_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplierinvoiceno', models.CharField(default=True, max_length=225)),
                ('partyAccntname', models.CharField(default=True, max_length=225)),
                ('currentbalancep', models.CharField(max_length=225, null=True)),
                ('currentbalancepl', models.CharField(max_length=225, null=True)),
                ('purchaseledger', models.CharField(default=True, max_length=225)),
                ('nameofitem', models.CharField(max_length=225, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('purchase_date', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partyAccntname', models.CharField(max_length=225)),
                ('currentbalancep', models.CharField(max_length=225, null=True)),
                ('salesledger', models.CharField(max_length=225)),
                ('currentbalancesl', models.IntegerField(null=True)),
                ('nameofitem', models.CharField(max_length=225, null=True)),
                ('quantity', models.IntegerField(null=True)),
                ('price', models.IntegerField(default=0)),
                ('sales_date', models.DateField(null=True)),
                ('total', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Particular',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particularsby', models.CharField(max_length=225, null=True)),
                ('particularsto', models.CharField(max_length=225, null=True)),
                ('credit', models.IntegerField(default=0, null=True)),
                ('debit', models.IntegerField(default=0, null=True)),
                ('journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app1.journal')),
            ],
        ),
    ]
