# Generated by Django 3.2.13 on 2022-09-05 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0015_auto_20220905_1429'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ledger_vouchers',
            name='ledgervoucher_date',
        ),
    ]
